# Generated by Django 4.1.6 on 2023-02-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
    ]
