# Generated by Django 4.1.6 on 2023-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_category_picture_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
