# Generated by Django 4.1.6 on 2023-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0024_alter_category_picture_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.CharField(max_length=600),
        ),
    ]
